### ISSUE TITLE
Skyblocker sending invalid packets

### ISSUE THREAD

**Issue by Julienraptor01** [SkyblockerMod/Skyblocker#1016]
### What happened?

1. make a 1.21.1 Fabric instance
1. add skyblocker and fabric API
1. launch the game
1. go on hypixel skyblock
1. open the skyblock crafting screen
1. middle click on the + while having any item in your cursor itemstack
1. wait half a second
1. get kicked

### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

skyblocker-1.22.2+1.21.1.jar

### Additional context

Analysis :
This is the packet that gets sent
```json
{
	"button_num": 2,
	"carried_item": {
		"components": {"..."},
		"item_count": 52,
		"item_id": 36
	},
	"changed_slots": {},
	"click_type": 3,
	"container_id": 4,
	"slot_num": -1,
	"state_id": 65
}
```
it's impossible to have -1 as slot num value in vanilla
additionally it's supposed to be impossible to middle click in survival
_however a vanilla bug allow it
but when it's done the click type is supposed to be 3 and the button is supposed to be 0_
there are other ways to cause this issue by using other types of custom UIs (elements) that skyblocker add such as the equipment preview or the value buttons

**Comment by kevinthegreat1** [comment]
Turns out this is reproducible in vanilla, so it's not our problem.
