### ISSUE TITLE
Always Sprint + HUD Indicator

### ISSUE THREAD

**Issue by VermeilChan** [SkyblockerMod/Skyblocker#1022]
### Describe the new feature.

Can you add an “Always Sprint” option? Similar to the Skytils, it would make sprint always active. A HUD indicator that shows if sprint is on would also be super helpful, so we don’t have to rely on the FOV change (which most players turn off anyway).

For a better example check [SimpleToggleSprint](https://github.com/My-Name-Is-Jeff/SimpleToggleSprint).

Why It’s Needed:
The current built-in toggle sprint works fine. But the problem is that it’s hard to tell if you’re sprinting or not without the FOV change. Since a lot of players (myself included) turn off the FOV effect because it’s distracting, there’s no clear way to know if sprint is active or not. Having a simple HUD indicator would fix this and make it much easier to keep track.

### Images

![image](https://github.com/user-attachments/assets/5408d226-3e2f-4525-84d7-1089e49e143c)
![image](https://github.com/user-attachments/assets/40cd91dd-6de8-4851-9583-c5940202af80)

**Comment by viciscat** [comment]
You can use this sprint indicator mod
https://modrinth.com/mod/sprint-indicator

**Comment by LifeIsAParadox** [comment]
“Always Sprint” option is already in vanilla.
Options -> Accessibility Settings... -> Sprint (Hold to Toggle)

**Comment by VermeilChan** [comment]
> You can use this sprint indicator mod https://modrinth.com/mod/sprint-indicator

alr ill try that

**Comment by VermeilChan** [comment]
> “Always Sprint” option is already in vanilla. Options -> Accessibility Settings... -> Sprint (Hold to Toggle)

my brain wasnt cooking, yes ik its build in minecraft, i need an indicator but illl try sprint-indicator first

**Comment by VermeilChan** [comment]
Okay [sprint-indicator](https://modrinth.com/mod/sprint-indicator) is good.
Thank you guys!!
