### ISSUE TITLE
ItemCooldowns#onItemInteract can be converted to a switch expression

### ISSUE THREAD

**Issue by kevinthegreat1** [SkyblockerMod/Skyblocker#1026]
### What happened?

title

### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

skyblocker-1.22.2-beta-47d0444+1.21.1

**Comment by AzureAaron** [comment]
This is already done in the amendment made to the `1.21.2-pre3` commit on the 1.21.2 branch.
