### ISSUE TITLE
allow to press the drop key when in dungeons and the item is in the hotbar

### ISSUE THREAD

**Issue by Emc2356** [SkyblockerMod/Skyblocker#1057]
### Describe the new feature.

when you are in dungeons and want to activate your ult you press q but if your item is protected (eg a terminator) you cant activate your ult.
I would suggest to allow to press the drop key if the inventory isnt open and you are inside of the dungeons

**Comment by x-yingcan-x** [comment]
see the `allowDroppingProtectedItems`(forget the exact name), this feature is already exist.
