### ISSUE TITLE
Incorrect Wizard Tower warp destination requirement

### ISSUE THREAD

**Issue by Manchick0** [SkyblockerMod/Skyblocker#1077]
### What happened?

Although it's an `epic` scroll, it's not actually required to be **MVP+** in order to use it. It's even more clear now, since the scroll is now purchasable from an NPC at the Wizard tower for 11,111 coins, and is marked as `rare` instead. 

Now, Wiki says otherwise and hasn't been updated to reflect the changes. It'd be worth changing the MVP+ requirement in the API to false.

### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

v1.23.0-beta.1+1.21.3

**Comment by lunaynx** [comment]
Yeah, plus there's the new Rift travel scroll which is now obtained from Roger, is also rare and doesn't require MVP+.

**Comment by LifeIsAParadox** [comment]
> Although it's an `epic` scroll, it's not actually required to be **MVP+** in order to use it. It's even more clear now, since the scroll is now purchasable from an NPC at the Wizard tower for 11,111 coins, and is marked as `rare` instead.

> Yeah, plus there's the new Rift travel scroll which is now obtained from Roger, is also rare and doesn't require MVP+.

Changed and added
