### ISSUE TITLE
Dungeon issues

### ISSUE THREAD

**Issue by Detlas-Legacy** [SkyblockerMod/Skyblocker#116]
Three weirdo solver does not work.
Displaying essence price in post boss chest would be nice.
Score calculations are sometimes incorrect.

**Comment by Julienraptor01** [comment]
> Three weirdo solver does not work.
> Displaying essence price in post boss chest would be nice.
> Score calculations are sometimes incorrect.

It does work, look at the color of their nametags after having clicked on all 3 of them

**Comment by Detlas-Legacy** [comment]
> > Three weirdo solver does not work.
> 
> It does work, look at the color of their nametags after having clicked on all 3 of them The one which has a green name is the one
> 
> > Displaying essence price in post boss chest would be nice.
> 
> Yes indeed it could, however it's kinda simple it's 2k/essence roughly iirc
> 
> > Score calculations are sometimes incorrect.
> 
> Afaik there is no score calculation in Skyblocker The only score you can see is the Hypixel one

1) Nope. All red. Options are on in modmenu.
2) Wither went as high as 2.7k like a month ago...
3) Okay.

**Comment by TheSilverBeluga** [comment]
It's a mod conflict with advancedchat. It breaks anything that involves getting text from chat.

**Comment by Detlas-Legacy** [comment]
> It's a mod conflict with advancedchat. It breaks anything that involves getting text from chat.


Oh thanks, it is indeeed that.
