### ISSUE TITLE
gui move up

### ISSUE THREAD

**Issue by Night-Reflection** [SkyblockerMod/Skyblocker#147]
well i tried both with the mod and without the mod on 1.19.4 fabric mod works but it moves gui up and make cursor weird i can be under the item or button with cursor yet i would still be able to click or use item/button. I made simble explonation in pinter 3d to explain
![image](https://user-images.githubusercontent.com/132771382/236634655-569dbe3b-cd2e-41c6-b821-4e5c3c70bd8d.png)
i dont know what could be the problem, i have never seen anything like that. Also this glitch **happens only when i log on skyblock**, in hypixel hub it works but as soon as i go to skyblock it happens

**Comment by AzureAaron** [comment]
Can you try and provide more information such as your game version, mod version and exactly where/how this happens?

**Comment by Julienraptor01** [comment]
Do you have any other mods installed, could you give us a log so we can help you better ?

**Comment by Night-Reflection** [comment]
> Can you try and provide more information such as your game version, mod version and exactly where/how this happens?

Game version I said in photo, mod version was 1.9.0 something i download the latest one possible. When i enter Skyblock UIs and GUIs go weird as i mentioned in photo

**Comment by Night-Reflection** [comment]
> Do you have any other mods installed, could you give us a log so we can help you better ?

I have no other mods, there is nothing in the log i checked it multiple times

**Comment by AzureAaron** [comment]
Could you upload a screenshot of this happening?

**Comment by Night-Reflection** [comment]
> Could you upload a screenshot of this happening?

I can't now but it is exactly as showed in the example photo.

**Comment by lantice3720** [comment]
![Screenshot_20230510-224859_Discord.jpg](https://github.com/SkyblockerMod/Skyblocker/assets/65650884/42381fd7-4c41-41cb-bfe2-8c4a700f6da3)

There is similar issue reported on discord. If you use feather client, it can be a reason.

**Comment by LifeIsAParadox** [comment]
Do you still have this issue? If so, could you give me this information:

- what operating system do you use
- what version of Skyblocker and Minecraft do you use
- beside of Skyblocker what other mod did you installed
