### ISSUE TITLE
I'm unsure if error is caused by this mod

### ISSUE THREAD

**Issue by Aces-and-Jacks** [SkyblockerMod/Skyblocker#161]
So in the sky block modpack whenever I go to sky block it spams ``Ignoring player info update for unknown player ee84fddc-9f77-4dc3-a811-310ef6fc0568`` in the log

https://mclo.gs/oIoOMCI

**Comment by Aces-and-Jacks** [comment]
It could just be culling but not sure if spamming in log from mob culling is a thing

**Comment by kevinthegreat1** [comment]
The log spamming is due to hypixel's multi version server. It is not caused by this mod.
