### ISSUE TITLE
Fancy Bars dont work with end armor

### ISSUE THREAD

**Issue by harrypotteryeah** [SkyblockerMod/Skyblocker#164]
when i have my end armor equipped and i go to the end my mana bar shows zero and my health and defense are the base values. I think because the stats of the end armor is doubled in the end. Also my chat gets spammed with item price info on tooltip will renew message every minute or so. I couldnt find a way to disable that please add a button. Also i suggest you add a save and exit button to the window you see when you quit without saving

**Comment by Julienraptor01** [comment]
can you give us the version of the mod ?

**Comment by harrypotteryeah** [comment]
1.18.2  what logs?

**Comment by Julienraptor01** [comment]
> 1.18.2  What logs? Even if its solved in further versions please fix the 1.18.2 as well

1.18.2 won't be fixed, please update
Backporting stuff to old version is very complicated and time consuming for no reason

**Comment by harrypotteryeah** [comment]
ok thanks but at least is there something i can do about the chat getting spammed by the item tooltip info will renew message

**Comment by Julienraptor01** [comment]
> ok thanks but at least is there something i can do about the chat getting spammed by the item tooltip info will renew message

Updating is the only way, because APIs and stuff where changed and the old one can't be used anymore

**Comment by harrypotteryeah** [comment]
ok thanks anyways
