### ISSUE TITLE
Custom Tab HUD Feedback

### ISSUE THREAD

**Issue by Kolobok125040** [SkyblockerMod/Skyblocker#175]
The new custom Tab HUD feature is very cool!
But I would like to be able to move this HUD to its normal location. When it's in the middle of the screen it's a bit confusing.
Also in the Garden I would like to see the time left until the next Jacob`s Contest, that would be very useful.

**Comment by AzureAaron** [comment]
> The new custom Tab HUD feature is very cool!
> But I would like to be able to move this HUD to its normal location. When it's in the middle of the screen it's a bit confusing.
> Also in the Garden I would like to see the time left until the next Jacob`s Contest, that would be very useful.

In the garden if you access the general info tab you can see time until next contest

**Comment by Kolobok125040** [comment]
> > The new custom Tab HUD feature is very cool!
> > But I would like to be able to move this HUD to its normal location. When it's in the middle of the screen it's a bit confusing.
> > Also in the Garden I would like to see the time left until the next Jacob`s Contest, that would be very useful.
> 
> In the garden if you access the general info tab you can see time until next contest

Oh, you can really do that there. I didn't know there were special bindings for that. (you can change them in the control settings)
And is it possible to select which mode is displayed by default when Tab is pressed?
