### ISSUE TITLE
Couldn`t load bags on 1.20 beta

### ISSUE THREAD

**Issue by TheMychenik** [SkyblockerMod/Skyblocker#199]
![image](https://github.com/SkyblockerMod/Skyblocker/assets/46868290/bcd209eb-966d-4a33-9710-81df19ea8eaf)
As you can see down left i could not open bags tab)

**Comment by TheMychenik** [comment]
All other tabs works

UPD: Add private island tab pls, like hub and dungeons

**Comment by TheMychenik** [comment]
Storage works, i will make a video, wait pls

**Comment by TheMychenik** [comment]
https://github.com/SkyblockerMod/Skyblocker/assets/46868290/ed2c50a8-d292-4fc6-8503-3270548bee9d

Im sorry for such video, shadowplay decided not to work. Btw storage works, bags not

**Comment by Julienraptor01** [comment]
oh sorry bags, i mixed them up in my head, do you have access to the sack of sacks ? (ClownFish IV)
you can also try / sacks to open them
if you have access to it, you should be able to open it via the skyblock menu -> your bags
![image](https://github.com/SkyblockerMod/Skyblocker/assets/49841713/32da94ea-3ada-4336-b675-dca914416bc4)

**Comment by Julienraptor01** [comment]
> No, i dont have it yet, i thought it will open bags not sacks) Now i got it, probably it needs renaming.
> 
> ![image](https://user-images.githubusercontent.com/46868290/252354879-a0d8bd91-8e50-499b-af1b-4755d19cac2f.png) Idk if its mod msg or hypixel. But it confuses

this message come from the server, not us

**Comment by TheMychenik** [comment]
Ok, my fault sorry. At least maybe if other people get confused like me they can find this page

**Comment by Julienraptor01** [comment]
> Ok, my fault sorry. At least maybe if other people get confused like me they can find this page

tbh, from what i see from GH issues, most don't XD, but we'll be able to link this page tho :)
if the message is really problematic, you can try to do a post on Hypixel forums to ask to change it

**Comment by TheMychenik** [comment]
Hah, maybe i will. Tnx for help, i close this.
