### ISSUE TITLE
SkyBlocker's behavoir when it can't get lbins/1-3d avgs

### ISSUE THREAD

**Issue by Fluboxer** [SkyblockerMod/Skyblocker#227]
So long story short - I got either ISPed/CFd and was unable to reach servers where lbins and 1-3d avgs are stored. However, I'm here not to cry about stupid ISP not rebooting their router but rather to talk about how skyblocker acts when that stuff happens:
1. When it attempts to get fresh prices, it purges whatever it had before, even if grabbing new prices fails 
2. There is no fallback options. Does only one single server on the planet have lbins for skyblock?
3. There is no caching in case shit happens
4. It proceeds to try every single minute, spamming logs and chat
![41322353453453](https://github.com/SkyblockerMod/Skyblocker/assets/36457056/1757bce8-f23d-4fc0-9b43-9d96b0daad12)

Stuff like "server is down", "ISP's shenanigans" and "cloudflare said no" can happen from time to time, so I believe making few tweaks would make it much more reliable:
1. Don't purge old prices if new ones fail to load; instead cache prices and if update fails - notify user about it and add in lore of item something like "cached prices, %n minutes old". Having prices that are 5 minutes old is way better than not having any. For very old prices (1h+ old) use a bit different description that tells about prices not being updated for a long time 
2. If there are other servers that can provide prices - add them as fallback option
3. After failing few 1-minute attempts to get prices tell user about them being unable to reach servers with prices and start checking in longer intervals (5-10 minutes), notify user on success. There is also should be command to manually try to reload prices 
4. Make logs include what exactly mod failed to reach so user don't have to go look it up in source code 
5. ^ all this stuff probably need some settings to be not annoying

**Comment by Julienraptor01** [comment]
Maybe 1. could be done
2. Probably isn't possible due to other servers if they exist potentially having different data formats, and having multiple datafixer would be a pain to maintain
For 3. Maybe but it adds logic complexity
4. Logs do indeed include what failed iirc, it include the URL
A simple solution to your problem is to try other DNSes
You can try cloudflare, Google or others, maybe another than the one you are using RN will work better
