### ISSUE TITLE
Quick buttons

### ISSUE THREAD

**Issue by xxLSD** [SkyblockerMod/Skyblocker#236]
I wanted to change the icons of the quick buttons in the "E" menu, but I did not succeed, because I do not know the NBT id of the items
Help please

**Comment by Julienraptor01** [comment]
well you can use mods such as https://modrinth.com/mod/nbttooltip to see the nbt (i know the mod i link here isn't updated to 1.20.1 but i'm in the process of updating it)

**Comment by xxLSD** [comment]
oh, ty so much

**Comment by Julienraptor01** [comment]
a 1.20.1 version is available there : https://nightly.link/Julienraptor01/NBTTooltip/suites/14963266909/artifacts/853464919
