### ISSUE TITLE
Highlights bug out when item tooltip appears while DulkirMod is installed

### ISSUE THREAD

**Issue by Tetro48** [SkyblockerMod/Skyblocker#239]
Mods to replicate this bug:
- Fabric API
- Fabric Language Kotlin
- [DulkirMod-Fabric](https://github.com/inglettronald/DulkirMod-Fabric)
- Skyblocker

Expected behavior (w/o DulkirMod):
- Croesus:
![image](https://github.com/SkyblockerMod/Skyblocker/assets/76738929/142d7b33-d51e-4254-888a-de433a586077)
- Croesus, when floor with no more chests to open is hovered over:
![image](https://github.com/SkyblockerMod/Skyblocker/assets/76738929/95135a65-ea86-4e4b-b14c-2bd53407a0be)

Actual behavior (w/ DulkirMod):
- Croesus, when floor with no more chests to open is hovered over:
![image](https://github.com/SkyblockerMod/Skyblocker/assets/76738929/ad6623bd-bccf-4283-9ae1-781631c680cd)
Drags transparent gray box by tooltip's position, and it also gets scaled by tooltip scale. This behavior is likely not intended.

This bug may result in solvers sometimes seemingly not working when you have DulkirMod installed.

**Comment by kevinthegreat1** [comment]
I just checked that we are using standard practices and the Screen Api. Seems like the matrix stack is not being popped after rending the tooltip. The gray boxes are rendered after tooltips. Dulkir might be doing something weird. Can you please provide your logs and report this to Dulkir too. I might look into it.

**Comment by kevinthegreat1** [comment]
Does this happen with other solvers (ie experiments)? If so then this would be somewhat pretty high priority.

**Comment by Tetro48** [comment]
This bug affects color highlighter itself, so, pretty much every solver using it are affected.

**Comment by kevinthegreat1** [comment]
This is a Dulkir bug, and I have reported it to them. Removing bug label.

**Comment by AzureAaron** [comment]
Dulkir has fixed this although I don't think a new version with the fix was released so you would have to build the mod for yourself.
