### ISSUE TITLE
Request support for EMI mods

### ISSUE THREAD

**Issue by ItzGreenCat** [SkyblockerMod/Skyblocker#249]
I've heard that this mod adapts to REI, but the plugin overload of R EI often causes the game to freeze or crash, and EMI has a recipe tree feature that works very well, so I would like to request that support for EMI be added

**Comment by kevinthegreat1** [comment]
[Here](https://github.com/SkyblockerMod/Skyblocker/files/12505168/skyblocker-1.12.0%2B1.20.1.jar.zip) is a test build. There're still some stuff that needs to be figured out, but this should work pretty well. If you want, you can also build from source from [this branch](https://github.com/kevinthegreat1/Skyblocker/tree/emi-integration).
