### ISSUE TITLE
Unable to detect Hypixel when connecting through proxies

### ISSUE THREAD

**Issue by ItzGreenCat** [SkyblockerMod/Skyblocker#250]
I installed the latest version of SkyBlocker Mod and can also see it in ModMenu, but nothing works after entering the game, but version 1.11.0 works (both my Fabric and Fabric APIs are up to date)

**Comment by AzureAaron** [comment]
What IP are you using to connect?

**Comment by ItzGreenCat** [comment]
hyp-1.xuegao123.net
this is a Accelerate IP,At my area if use mc.hypixel.net or mc.hypixel.io Causes huge lags,like 2000~5000 ms
So here is a spceial ip can let ping back to playable,like 180~250 ms

**Comment by ItzGreenCat** [comment]
hyp-1.xuegao123.net
this is a Accelerate IP,At my area if use mc.hypixel.net or mc.hypixel.io Causes huge lags,like 2000 - 5000 ms
So here is a spceial ip can let ping back to playable,like 180 - 250 ms

**Comment by PumpkinXD** [comment]
> What IP are you using to connect?

some players using proxies to reduce ping/loss in my country

some proxies are IPs that can be connected like ```mc.hypixel.net```
