### ISSUE TITLE
Secret Mod does not count bat if it is killed by frozen blaze

### ISSUE THREAD

**Issue by enbyte** [SkyblockerMod/Skyblocker#279]
### What happened?

Get full set of fb
Go to a secret bar
Observe bat dying, damage tick, bestiary increase
Brown marker stays there

### Minecraft Version

1.20

### Skyblocker Version

1.12.0+1.20

**Comment by AzureAaron** [comment]
Perhaps we could do a check for when a bat is removed within a range of the secret waypoint

**Comment by RockTheDev** [comment]
I have to note, that I find a lot of rooms having "bat" beacon, but no actual bat (chest or item drop at best). Not sure if it's a bug on the hypixel network or on the mods side. 1.20.1

**Comment by AzureAaron** [comment]
> I have to note, that I find a lot of rooms having "bat" beacon, but no actual bat (chest or item drop at best). Not sure if it's a bug on the hypixel network or on the mods side. 1.20.1

Some bats in dungeons automatically die

**Comment by RockTheDev** [comment]
> > I have to note, that I find a lot of rooms having "bat" beacon, but no actual bat (chest or item drop at best). Not sure if it's a bug on the hypixel network or on the mods side. 1.20.1
> 
> Some bats in dungeons automatically die

And the marker never gets removed off the map, unless you do all of the secrets. Hopefully it somehow can be fixed.
