### ISSUE TITLE
Add settings that can modify the distance of Teleport Overlay

### ISSUE THREAD

**Issue by contionability** [SkyblockerMod/Skyblocker#282]
### Describe the new feature.

as you can see, Transmission Tuner can extend the teleport distance.

### Images

![图片](https://github.com/SkyblockerMod/Skyblocker/assets/78670017/55fb0788-ef28-43ab-acca-fe66592d9a11)

**Comment by Julienraptor01** [comment]
> 

it's already implemented and handled by the code
https://github.com/SkyblockerMod/Skyblocker/blob/9c7bf54123f366ad90bfafe81e973b731fd6b5b3/src/main/java/me/xmrvizzy/skyblocker/skyblock/TeleportOverlay.java#L32-L76

**Comment by contionability** [comment]
I downloaded the latest ver and found it work properly
maybe there was a problem with my prev version
thanks for the reply
