### ISSUE TITLE
Item List not Working

### ISSUE THREAD

**Issue by Baulybubble** [SkyblockerMod/Skyblocker#303]
### What happened?

The item list just says "loading," and REI/EMI also does not show skyblock items.

### Screenshots

![image](https://github.com/SkyblockerMod/Skyblocker/assets/132310363/13a06a7b-eb86-4c42-8b9c-244ae5a1dfcb)

### Log output

[latest.log](https://github.com/SkyblockerMod/Skyblocker/files/12614844/latest.log)

### Minecraft Version

Minecraft 1.20.1

### Skyblocker Version

skyblocker-1.13.0+1.20.1.jar

**Comment by AzureAaron** [comment]
Going to close as I cannot reproduce this on the latest beta version (1.20.4), if you encounter further trouble join the discord and create a support thread :)
