### ISSUE TITLE
Player heads don't show when viewing default view

### ISSUE THREAD

**Issue by Aces-and-Jacks** [SkyblockerMod/Skyblocker#327]
### What happened?

When I show the default view, player heads are missing

### Screenshots

<img width="1512" alt="Screen Shot 2023-09-22 at 10 18 49 PM" src="https://github.com/SkyblockerMod/Skyblocker/assets/106651342/b959d133-b927-4bbe-9c18-27e088cd063e">

### Log output

https://mclo.gs/QbsOrQK

### Minecraft Version

Minecraft 1.20.1

### Skyblocker Version

Skyblocker 1.14.0 for 1.20.1

**Comment by Julienraptor01** [comment]
This is a hypixel bug, not a bug of ours

**Comment by Aces-and-Jacks** [comment]
Ok, thank you. Also do you know if there's an option that makes the experience bar disappear or is that just something from a different mod

**Comment by Julienraptor01** [comment]
> Ok, thank you. Also do you know if there's an option that makes the experience bar disappear or is that just something from a different mod

We have a feature called fancy bars in our mod, tho they seem disabled or overriden by another mod in your screenshot

**Comment by Aces-and-Jacks** [comment]
found it. Thanks
