### ISSUE TITLE
Backpack Preview does not work with custom texture packs and other features

### ISSUE THREAD

**Issue by kevinthegreat1** [SkyblockerMod/Skyblocker#351]
### What happened?

The custom texture pack is not applied in Backpack Preview
Item Rarity Background also does not affect items in Backpack Preview.

### Screenshots

<img width="1440" alt="BackpackPreview" src="https://github.com/SkyblockerMod/Skyblocker/assets/92656833/f9d64648-f0e2-4eb7-b8c3-d4a263051aeb">

### Minecraft Version

Minecraft 1.20.2

### Skyblocker Version

skyblocker-1.14.0-beta+1.20.2

**Comment by kevinthegreat1** [comment]
Idk how easy this is to fix so I just opened an issue.

**Comment by AzureAaron** [comment]
This was intentional, attempting to render it broke Z-layering
