### ISSUE TITLE
EMI Recipe Tree Doesn't Work

### ISSUE THREAD

**Issue by ItzGreenCat** [SkyblockerMod/Skyblocker#358]
### What happened?

Just like title,The Recipe Tree Cannot Work,It Always show vanilla's item or not show recipe

### Screenshots

![2023-10-12 16-46-31屏幕截图](https://github.com/SkyblockerMod/Skyblocker/assets/114486129/eb81e8cf-ea90-47fe-b3ea-0357a5a4884a)

### Log output

That no need a log i guess

### Minecraft Version

Minecraft 1.20.1

### Skyblocker Version

skyblocker-1.14.0+1.20.1.jar

**Comment by kevinthegreat1** [comment]
I am unable to reproduce the issue. Do note that this feature depends on [NotEnoughUpdates-REPO](https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO) loading properly. If you are still having issue, please attach your logs.

<img width="1440" alt="Screenshot 2023-10-15 at 21 03 06" src="https://github.com/SkyblockerMod/Skyblocker/assets/92656833/6c65621a-326a-4113-ab61-eded473a68b6">

**Comment by ItzGreenCat** [comment]
i cannot provide a exactly file because every time i launch game and try this feature it wont work

**Comment by ItzGreenCat** [comment]
> I am unable to reproduce the issue. Do note that this feature depends on [NotEnoughUpdates-REPO](https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO) loading properly. If you are still having issue, please attach your logs.
> <img alt="Screenshot 2023-10-15 at 21 03 06" width="1440" src="https://user-images.githubusercontent.com/92656833/275366680-6c65621a-326a-4113-ab61-eded473a68b6.png">

i see this image again and i found u already reproduce this issue,look at this repice tree,its right at first step,but at the second step(craft spongy boots) it will use the vanilla repice (look that image , it shows 4 leather , that's vanilla leather boots repice , not skyblock spongy boots repice)
