### ISSUE TITLE
Crash on start-up

### ISSUE THREAD

**Issue by Awoolanche** [SkyblockerMod/Skyblocker#368]
### Minecraft Version

1.20.1

### Skyblocker Version

skyblocker-1.14.0+1.20.1, skyblocker-1.14.1+1.20.1

### Reproduction Steps

1. Install Skyblocker and required dependencies,
2. Launch the game.

### Crash Report file and latest.log

```shell
https://mclo.gs/kdfwCRv
```

**Comment by 0xallie** [comment]
It doesn't seem to be what's causing the issue, but I noticed you have ImmediatelyFast 1.20.2 installed on 1.20.1. That may also cause the problems.

**Comment by LifeIsAParadox** [comment]
The issue is related to the Crystal Launcher you're using. I installed the same mods and tested them on both the Prism Launcher and the Crystal Launcher. I didn't encounter any problems on the Prism Launcher, but I experienced a crash on the Crystal Launcher, just like you did.

**Comment by LifeIsAParadox** [comment]
found a solution you have to click on "disable Cystal Launcher skin system" under Settings -> Advanced -> disable Cystal Launcher skin system
![Bildschirmfoto vom 2023-10-20 10-57-31](https://github.com/SkyblockerMod/Skyblocker/assets/19829407/e40b21af-b9a8-49ba-8b0b-df2ddb5d0c42)
