### ISSUE TITLE
Creeper solver doesn't always work

### ISSUE THREAD

**Issue by msg-programs** [SkyblockerMod/Skyblocker#392]
### What happened?

The darn thing failed on me just now and produced a solution that didn't solve the puzzle. Might be that the position I use for the calculations (center of the block 3 blocks above the target in the base) is just a bit off. Not sure if hardcoding the "free" beam solves the issue, as a wrong solution may still be closer to the faulty target position than a correct one in the three beams one still needs to find.

### Minecraft Version

1.20.2

### Skyblocker Version

1.14.0+1.20.2

**Comment by msg-programs** [comment]
Update: Looked a bit harder, 2-2.5 blocks instead of 3.5 should be better. This'll also make the "free" solution more likely if not guaranteed.

**Comment by kevinthegreat1** [comment]
Fixed in #396
