### ISSUE TITLE
Mythological ritual solver have weird semi-transparent rectangles

### ISSUE THREAD

**Issue by Fluboxer** [SkyblockerMod/Skyblocker#398]
### What happened?

Those seem to be either debug part that weren't removed or _very_ scuffed thing to show path

### Screenshots

![изображение](https://github.com/SkyblockerMod/Skyblocker/assets/36457056/1eeb58e0-5547-4437-ba43-73a80d982d6a)
![изображение](https://github.com/SkyblockerMod/Skyblocker/assets/36457056/a42497db-5798-4109-94cd-e57f8fcedbb1)
![изображение](https://github.com/SkyblockerMod/Skyblocker/assets/36457056/ee815002-f1c0-422d-b7fa-348fc89b8e7f)

### Minecraft Version

1.20.2

### Skyblocker Version

skyblocker-1.15.0-beta-5bb9110+1.20.2.jar

### Additional context

OS: Astra Linux (5.15.0)
Fabric 0.14.22; Fabric API 0.90.4
YACL 3.3.0; ModMenu 8.0.0

When rechecking for this issue, I disabled other mods, including all sorts of optimization mods (IF, Sodium, etc), to make sure that this issue persists. With those this bug also were a thing (first two screenshots)

also attaching config file just in case: [skyblocker.json](https://github.com/SkyblockerMod/Skyblocker/files/13230157/skyblocker.json)

**Comment by kevinthegreat1** [comment]
Yeah, this shows the path. Any suggestions on how I should do it?

**Comment by Fluboxer** [comment]
> Yeah, this shows the path. Any suggestions on how I should do it?

If it possible to triangulate location of next burrow - use this and just show place prediction for player to go there as waypoint. If it will be a thing, showing path would be optional
 
Speaking about path - just draw fat line towards direction instead of cursed rectangle 
P.S. Also another mini-request - different waypoint color for fresh untouched burrows so it would be less confusing with one you already doing
