### ISSUE TITLE
Wrong dungeon secrets number when connection failed

### ISSUE THREAD

**Issue by x-yingcan-x** [SkyblockerMod/Skyblocker#408]
### What happened?

secrets found by me always negative number and other people are less than they actually found

### Screenshots

![sshot-2023-11-04-15-17-13](https://github.com/SkyblockerMod/Skyblocker/assets/99530733/a0717c65-8d6d-469f-980a-55cd7c791cc5)
![2023-11-03_23 27 34](https://github.com/SkyblockerMod/Skyblocker/assets/99530733/3a429ac6-41f4-4dd2-893a-dc2cac380a91)

### Log output

2 solo f2 runs
[normalPlayWithOtherMods.log](https://github.com/SkyblockerMod/Skyblocker/files/13256099/normalPlayWithOtherMods.log)
[skyblocker+YACL+FAPI+sodium.log](https://github.com/SkyblockerMod/Skyblocker/files/13256100/skyblocker%2BYACL%2BFAPI%2Bsodium.log)

### Minecraft Version

1.20.2

### Skyblocker Version

skyblocker-1.15.0-beta-48e7f23+1.20.2

**Comment by AzureAaron** [comment]
The negative secrets comes from the fact that the HTTP connection to the API was reset for whatever reason, nothing we have control over. The api is also cached for 5 minutes which may play weirdly with runs shorter than that period.

**Comment by x-yingcan-x** [comment]
is it possible to send extra requires for correct result or just tell me it failed
anyway, thanks
