### ISSUE TITLE
Snap aim feature 

### ISSUE THREAD

**Issue by Kolobok125040** [SkyblockerMod/Skyblocker#431]
### Describe the new feature.

Snap aim feature for garden like in [Tweakeroo](https://www.curseforge.com/minecraft/mc-mods/tweakeroo). Here video -> [Click](https://www.youtube.com/watch?v=oh7Zbzy5oew)

**Comment by alexiayaa** [comment]
This sounds potentially risky. While currently it is not flagged by watchdog, I would only let it snap tiny distances like [CardinalAlign](https://github.com/ptlthg/CardinalAlign) to be on the safe side. And farmers don't like recommending even *that* mod.

**Comment by kevinthegreat1** [comment]
I believe this is risky. You can use Tweakeroo. Additionally, this feature seems to be more general utility and not suitable for this mod.

**Comment by AzureAaron** [comment]
While we won't be adding an aim snapping feature, we will add a feature that will allow you to lock your sensitivity in #607.
