### ISSUE TITLE
Experiments issues

### ISSUE THREAD

**Issue by Julienraptor01** [SkyblockerMod/Skyblocker#435]
### What happened?

- The [Chronomatron](https://wiki.hypixel.net/Experimentation_Table#Chronomatron) and the [Ultrasequencer](https://wiki.hypixel.net/Experimentation_Table#Ultrasequencer) can break if you go too fast (especially the chronomatron if you have 2+ clicks on the same note) or if you get connection lag spikes while doing them
- The [Superpairs](https://wiki.hypixel.net/Experimentation_Table#Superpairs) don't properly continue to reveal the items on the last click

### Minecraft Version

1.20.2 | older versions are affected too

### Skyblocker Version

1.16.0 | older versions are affected too

### Additional context

Theses exist since the solvers existed in [SkyblockMod](https://github.com/kevinthegreat1/SkyblockMod-Fabric)

**Comment by kevinthegreat1** [comment]
Can you see if #437 fixes the issue with Superpairs?  

The other two solvers shouldn't break when you go too fast, I just checked. I think the game is doing some weird stuff when you click too fast.
