### ISSUE TITLE
Crash (Auction House)

### ISSUE THREAD

**Issue by senisditron** [SkyblockerMod/Skyblocker#440]
### Minecraft Version

1.20.2

### Skyblocker Version

 skyblocker-1.16.0+1.20.2.jar 

### Reproduction Steps

1.Go to action house 
2.Click on npc then auction browser 
3.Game crash 

### Crash Report file and latest.log

```shell
Logs below
```

### Additional context

[latest.log](https://github.com/SkyblockerMod/Skyblocker/files/13537838/latest.log)
[crash-2023-12-03_02.47.34-client.txt](https://github.com/SkyblockerMod/Skyblocker/files/13537842/crash-2023-12-03_02.47.34-client.txt)

**Comment by kevinthegreat1** [comment]
This seems to be an incompatibility with feather. They are closed source so it's basically impossible for us to fix this on our end. In addition, there seems to be some controversy with feather: https://hypixel.net/threads/feather-client-what-you-should-know-about-this-client.4801748/ and https://hypixel.net/threads/why-feather-client-is-lying-to-you.4842120/.
