### ISSUE TITLE
Drill fuel feature conflicts with any durability viewer mod

### ISSUE THREAD

**Issue by minhperry** [SkyblockerMod/Skyblocker#459]
### Minecraft Version

1.20.2

### Skyblocker Version

1.16.0+1.20.2

### Reproduction Steps

~~1. Enable Preview Backpack feature to be Yes
2. Open backpack for it to cache
3. After few opened you will be kicked for StackOverflow error
4. Relog, open more and the game would crash~~.

1. Enable drill fuel
2. Open a backpack that contains the drill in it
3. Game crashes because of StackOverflowError

### Crash Report file and latest.log

Crash log:
https://mclo.gs/EexOne7

Lastest.log:
https://mclo.gs/N4L4mrL

### Additional context

This somehow might be related to me being kicked also from StackOverflowError (not crashed, nothing in log either) from opening my backpacks.

IGN worst\_ht\_player

**Comment by minhperry** [comment]
Edit: this seems like a conflict with Duraibility Tooltip

**Comment by minhperry** [comment]
the drill fuel feature conflicts with ANY durability viewer mod

**Comment by kevinthegreat1** [comment]
Thanks for the report, I'll look into it. Probably fixable on our end.

**Comment by minhperry** [comment]
Edited the title to reflex more on the bug

**Comment by minhperry** [comment]
Edited the title and description to reflex more on the bug
