### ISSUE TITLE
1.20 update

### ISSUE THREAD

**Issue by virus00020** [SkyblockerMod/Skyblocker#470]
### What happened?

i would like a version of the lastest update in 1.20, i want to get all of the new updates, new things 

### Minecraft Version

1.20

### Skyblocker Version

nothing

**Comment by AzureAaron** [comment]
Backports for older versions are not planned especially given the effort, if you would like to get the latest features and bug fixes I highly recommend updating to 1.20.4 and downloading the latest version of the mod or the betas.
