### ISSUE TITLE
Outdated pack format for top aligned tab hud

### ISSUE THREAD

**Issue by AzureAaron** [SkyblockerMod/Skyblocker#491]
### What happened?

The Skyblocker tab hud top aligned pack displays as outdated and erroneously presents the user with a warning when trying to enable it. the pack format has to be updated (1.20.4)

### Minecraft Version

1.20.2

### Skyblocker Version

skyblocker-1.16.0+1.20.4

**Comment by Thsgun** [comment]
couldnt you change the pack format to 18 and call it a day?
