### ISSUE TITLE
Make a keybind feature (for commands)

### ISSUE THREAD

**Issue by m0ving** [SkyblockerMod/Skyblocker#498]
### Describe the new feature.

Make it so that you can keybind a command to a key on the keyboard, similar to skytils. Ex: /warp hub bound to "k" on keyboard.

**Comment by alexytomi** [comment]
There's already a different mod that does that tho.

https://modrinth.com/mod/command-keys

Would be nice as a feature in the mod itself though. Especially dungeon waypoints

**Comment by m0ving** [comment]
I didn't know about this, thanks.
