### ISSUE TITLE
Item DFU doesn't fix up banner data

### ISSUE THREAD

**Issue by AzureAaron** [SkyblockerMod/Skyblocker#499]
### What happened?

The mod's DFU for items cannot fix up banner data resulting in items like the Totem of Corruption appearing as plain white banners without any patterns.

### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.16.0+1.20.4.jar

**Comment by Julienraptor01** [comment]
DFU doesn't fix potions either
Basically anything related to additional metadata is currently not datafixed

**Comment by AzureAaron** [comment]
> DFU doesn't fix potions either Basically anything related to additional metadata in newer version is currently not datafixed
> 
> Like we have a convertItemId, we should probably designe a convertItemNBT that handle doing all NBTs transformations
> 
> https://github.com/SkyblockerMod/Skyblocker/blob/0d6ae155fb799bcd0932cb6633f03bd73df2c9c3/src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemFixerUpper.java#L299
> 
> 
> https://github.com/SkyblockerMod/Skyblocker/blob/0d6ae155fb799bcd0932cb6633f03bd73df2c9c3/src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemStackBuilder.java#L39
> 
> That's one of the improvements i had partially done on my 1.19.2 fork, so i can try to upstream theses changes I'll try to do it in about a week when my exam session finishes

I also wonder to an extent if it'd be possible to use Mojang's DFU for some of this stuff.

**Comment by Julienraptor01** [comment]
> > DFU doesn't fix potions either Basically anything related to additional metadata in newer version is currently not datafixed
> > 
> > Like we have a convertItemId, we should probably designe a convertItemNBT that handle doing all NBTs transformations
> > 
> > https://github.com/SkyblockerMod/Skyblocker/blob/0d6ae155fb799bcd0932cb6633f03bd73df2c9c3/src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemFixerUpper.java#L299
> > 
> > 
> > https://github.com/SkyblockerMod/Skyblocker/blob/0d6ae155fb799bcd0932cb6633f03bd73df2c9c3/src/main/java/de/hysky/skyblocker/skyblock/itemlist/ItemStackBuilder.java#L39
> > 
> > That's one of the improvements i had partially done on my 1.19.2 fork, so i can try to upstream theses changes I'll try to do it in about a week when my exam session finishes
> 
> I also wonder to an extent if it'd be possible to use Mojang's DFU for some of this stuff.

Maybe ? That could be an idea to investigate
Another thing we could investigate is setup up our own items repo with things already datafixed
