### ISSUE TITLE
DungeonSecretWidget has wrong indexes for secrets and crypts

### ISSUE THREAD

**Issue by Emirlol** [SkyblockerMod/Skyblocker#503]
### What happened?

When class milestone 9 is reached, the discoveries section moves up by 1 (so the index is 1 lower). Currently the widget has the indexes for that situation and breaks if class milestone isn't 9 yet, showing discovery count in secrets count and secrets count in crypts count.
To be specific: 

### Class milestone == 9 indexes (current)
- Secrets: 31
- Crypts: 32

### Class milestone != 9 indexes
- Secrets: 32
- Crypts: 33

I couldn't think of a clean way to solve this, so I'm leaving this as an issue to whoever might want to tackle this issue.

### Minecraft Version

1.20.4

### Skyblocker Version

Seems to be wrong since the initial commit, so it doesn't matter

**Comment by AzureAaron** [comment]
Well it wasn't really wrong, Hypixel just added the class milestone thing and it was never updated.
