### ISSUE TITLE
Livid solver breaks if server lags 

### ISSUE THREAD

**Issue by Fluboxer** [SkyblockerMod/Skyblocker#539]
### What happened?

2 bugs for one thing YAY

So thing at ceiling before fight starts is RED, but it changes when it starts. However, server sometimes lags and solver may say "color is RED" while real color is different

### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.17.0-beta-7aaf222+1.20.4.jar

**Comment by kevinthegreat1** [comment]
Don't think this could be fixed, we have to say it's red at some point.

**Comment by Fluboxer** [comment]
Maybe recheck color from time to time? Would also fix 2nd issue
