### ISSUE TITLE
Experiments Solver Not Working

### ISSUE THREAD

**Issue by 10dnb** [SkyblockerMod/Skyblocker#555]
### What happened?

The experiments solver don't seem to work. I took out all the resourcepacks and still not showing.
Was hoping you could help me pinpoint what mod might be conflicting.

Thanks in advance!

### Screenshots

![mods1](https://github.com/SkyblockerMod/Skyblocker/assets/91121741/ceccd466-66ea-4c50-8b45-151b33e8b1a1)

### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.14.1+1.20.1

**Comment by x-yingcan-x** [comment]
`Replay` cause this issue.
**Update** your client and mods to **1.20.4**, it's not worth to backport to 1.20.1. I know this is pain, but we don't have choice.
_A log_ usually more helpful than a screenshot.

**Comment by x-yingcan-x** [comment]
It usually at `%your client%/logs/latest.log`, many launcher have a shortcut to it or to `%your client%`
`%your client%` is `.minecraft` or `.minecraft/version/..` or sth else (depend on your launcher and settings)
`latest.log` usually includes all info needed, send it whenever asking help for game crash
btw, close this issue as it has already fixed.
