### ISSUE TITLE
Can't click in Ultrasequencer

### ISSUE THREAD

**Issue by WhatYouThing** [SkyblockerMod/Skyblocker#566]
### What happened?

While using Skyblocker 1.18.0 it is impossible to do the Ultrasequencer add-on in the Experimentation Table. Every click is blocked even if the Ultrasequencer solver is disabled.

### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.18.0+1.20.4.jar

**Comment by kevinthegreat1** [comment]
Try disabling `Hide Empty Tooltips` for now. Working on a fix.
