### ISSUE TITLE
Skyblocker Displays Same Message Nonstop

### ISSUE THREAD

**Issue by TheRealGCZ** [SkyblockerMod/Skyblocker#575]
The dang mod keeps sending me this message through chat:
![image](https://github.com/SkyblockerMod/Skyblocker-modpack/assets/121911493/f4c0d123-d369-4472-be4a-34cbc5795ffc)
I have no idea how to turn it off, it won't stop sending, and it's really annoying.

**Comment by AzureAaron** [comment]
Related to #227

**Comment by AzureAaron** [comment]
The HTTP connection to the average LBIN server seems to be timing out, are you able to access the following URLs in a web browser?
https://moulberry.codes/auction_averages_lbin/1day.json
https://moulberry.codes/auction_averages_lbin/3day.json

When you try this share the results (perhaps a screenshot), I would recommend doing it on the exact same network as when you encountered this issue.

**Comment by TheRealGCZ** [comment]
Well, I guess it's a me-problem
![image](https://github.com/SkyblockerMod/Skyblocker/assets/121911493/1907a765-adc6-4d36-894e-e8eeb786e107)
![image](https://github.com/SkyblockerMod/Skyblocker/assets/121911493/29a01bd1-c0cf-47e5-81a1-f3b33ab2afa0)
Same network as before, same issue
Must be something on my end

Tested on a different network
![image](https://github.com/SkyblockerMod/Skyblocker/assets/121911493/728d7157-ca19-4fb0-b3eb-10919be7ae92)
![image](https://github.com/SkyblockerMod/Skyblocker/assets/121911493/d2fb1b5f-8b01-4aef-bd5e-1a2cc38f81a3)
Links work fine and don't time out
Spammy message is gone as well
I guess it's just a network issue

**Comment by AzureAaron** [comment]
> Well, I guess it's a me-problem ![image](https://private-user-images.githubusercontent.com/121911493/308338456-1907a765-adc6-4d36-894e-e8eeb786e107.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNzM1NTgsIm5iZiI6MTcwOTA3MzI1OCwicGF0aCI6Ii8xMjE5MTE0OTMvMzA4MzM4NDU2LTE5MDdhNzY1LWFkYzYtNGQzNi04OTRlLWU4ZWViNzg2ZTEwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QyMjM0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzUwZjQwZWE5MmQ0MzMyMGM2M2FlMjA0MGE1MjJiM2ViZTRhYzE1NmM5NGFkYzBlY2MxMzBmMjE4MDU1YTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rDIL-68KtFlq0UomgNIqmg8V1He3JLddzuZCeeck7sk) ![image](https://private-user-images.githubusercontent.com/121911493/308338482-29a01bd1-c0cf-47e5-81a1-f3b33ab2afa0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNzM1NTgsIm5iZiI6MTcwOTA3MzI1OCwicGF0aCI6Ii8xMjE5MTE0OTMvMzA4MzM4NDgyLTI5YTAxYmQxLWMwY2YtNDdlNS04MWExLWYzYjMzYWIyYWZhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QyMjM0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTg2OWNiNzM4MTkzMTIwZDU3YzJkODkzZDljZDJjNGI1M2VkMjgwZDU1ZDU3YzI5YmJmYzg4MTRkNTdlMjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mmg-6dCTkcqQYGoY1ZIpvRShR-2_p9AbXmxvW0na2fc) Same network as before, same issue Must be something on my end
> 
> Tested on a different network ![image](https://private-user-images.githubusercontent.com/121911493/308339459-728d7157-ca19-4fb0-b3eb-10919be7ae92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNzM1NTgsIm5iZiI6MTcwOTA3MzI1OCwicGF0aCI6Ii8xMjE5MTE0OTMvMzA4MzM5NDU5LTcyOGQ3MTU3LWNhMTktNGZiMC1iM2ViLTEwOTE5YmU3YWU5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QyMjM0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTg4ODAwMzA2OWZhZjNkZjNjNWRiOGYyZDQwNzI1NGIxNWI1YjMwYzNjODM1MmVkMzQ0OTE5NjUwMTk0NzA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ED8xMZlacvkMBhDA8QR3w_f5TDUv36btUpsYw2-oY1A) ![image](https://private-user-images.githubusercontent.com/121911493/308339507-d2fb1b5f-8b01-4aef-bd5e-1a2cc38f81a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNzM1NTgsIm5iZiI6MTcwOTA3MzI1OCwicGF0aCI6Ii8xMjE5MTE0OTMvMzA4MzM5NTA3LWQyZmIxYjVmLThiMDEtNGFlZi1iZDVlLTFhMmNjMzhmODFhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QyMjM0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTU5ZTdmZjQ4MzZhYTRjNjBiMWMyNzQ4YmE3MmYzODQxZWEwNzZlNGM2YWZiNjI5YzEyMjQwMGJiYjcyMjVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.caHVGdiGwe1-A0MFBOl5rrBoF_RX2cH8Fh5TV7iMFCU) Links work fine and don't time out Spammy message is gone as well I guess it's just a network issue

Are you using some kind of a network firewall? It might be that. A temporary workaround until we fix the message spam is to disable the Lowest bin average prices inside the price tooltip config.

**Comment by AzureAaron** [comment]
Closing as the message spam was fixed in #576. If you have further issues with the average lbin price tooltip data not loading I would suggest joining the discord and making a support thread so we can help debug it.
