### ISSUE TITLE
Somethings up with the F7 first device solver

### ISSUE THREAD

**Issue by notnotmelon** [SkyblockerMod/Skyblocker#581]
### What happened?

The simon says device solver in F7 seems to be broken. It seems to only highlight the correct button in purple about 20% of the time. The other 80% of the time nothing is highlighted. If it helps, my wife is encountering the same issue, so I don't think it's setup-related.

### Minecraft Version

1.20.4

### Skyblocker Version

v1.18.0+1.20.4

**Comment by AzureAaron** [comment]
Skyblocker does not have any device solvers yet. Are you sure you are using the correct game version & mod set?

**Comment by notnotmelon** [comment]
Dang, That's so weird
Here's my modlist

![image](https://github.com/SkyblockerMod/Skyblocker/assets/30201457/df58d958-1a3e-46b1-a3a7-0f383b9ca89f)
![image](https://github.com/SkyblockerMod/Skyblocker/assets/30201457/6dbef595-c6e9-451f-9292-83fa42d33f4f)

**Comment by x-yingcan-x** [comment]
send a screenshot of "_device solver_"? maybe just secret waypoints didnt clear
then we can close this
