### ISSUE TITLE
Dungeon secret waypoints bug

### ISSUE THREAD

**Issue by maDU59** [SkyblockerMod/Skyblocker#586]
### What happened?

Idk why but sometimes random secret waypoints appear, it happened to me in F6 boss room and creeper-beam puzzle room.

### Screenshots

![image](https://github.com/SkyblockerMod/Skyblocker/assets/76407125/00bb49e5-c506-43d5-8164-cc0b88559e2a)

### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.18.1+1.20.4

**Comment by kevinthegreat1** [comment]
We need your full logs. You can upload it to mclo.gs.

**Comment by kevinthegreat1** [comment]
Fixed in #597
