### ISSUE TITLE
Tab HUD update

### ISSUE THREAD

**Issue by AC19970** [SkyblockerMod/Skyblocker#598]
### What happened?

Hypixel has updated the HUD so that the mod's current method of only displaying data for specific locations in the menu no longer works. New ways are needed to make the HUD provided by the mod work properly. It would be best if it could be enabled even when the menu widget is not enabled.

### Minecraft Version

1.20.4

### Skyblocker Version

 skyblocker-1.18.1+1.20.4.jar

**Comment by R2kip** [comment]
![image](https://github.com/SkyblockerMod/Skyblocker/assets/56793105/f73b2e2c-3b5d-4ffe-bcdf-64384c06c68e)
