### ISSUE TITLE
Holding a Shortbow breaks Dungeons features

### ISSUE THREAD

**Issue by WhatYouThing** [SkyblockerMod/Skyblocker#600]
### What happened?

Since Skyblock v0.19.12 the game displays the type of arrow you're currently using by replacing the Skyblock Menu/Dungeon map with another item, and things like solvers or the map display refuse to work because of it.

### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.18.0+1.20.4.jar

**Comment by Julienraptor01** [comment]
We know and have started working on a fix, you can download a pre-version there : https://nightly.link/SkyblockerMod/Skyblocker/workflows/beta/master/skyblocker-1.18.1-beta-40fc055%2B1.20.4.zip

**Comment by WhatYouThing** [comment]
Didn't look at the beta branch, my bad
