### ISSUE TITLE
Skyblocker breaks most textures on texture pack

### ISSUE THREAD

**Issue by Ozzy146** [SkyblockerMod/Skyblocker#602]
### What happened?

I use the Hypixel+ texture pack which works normally with optifine. However, combining the texture pack and Skyblocker causes most textures to be glitched. Is there a setting which causes this or a fix to this because it would be nice to have both the texture pack and mod.

### Screenshots

![2024-03-17_12 50 29](https://github.com/SkyblockerMod/Skyblocker/assets/79716579/c4b5cbf6-bc5a-47d4-9df8-331cf752397c)

### Minecraft Version

1.20.4

### Skyblocker Version

1.18.1

**Comment by Julienraptor01** [comment]
What version of Hypixel+ are you using ?

**Comment by Ozzy146** [comment]
Im using "Hypixel+ 0.19.11 for 1.20.x"

**Comment by Julienraptor01** [comment]
Also OptiFine is not a setup that is supported, please use Fabric alternatives like sodium
If you want to have a good compat, look into the [skyblocker modpack](https://modrinth.com/modpack/skyblocker-modpack) or in [Fabulously Optimized](https://modrinth.com/modpack/fabulously-optimized)

**Comment by Ozzy146** [comment]
I'll give it a go now. I'm not sure it will work as the texture pack requires optifine to work.

**Comment by Julienraptor01** [comment]
> I'll give it a go now. I'm not sure it will work as the texture pack requires optifine to work.

No, the resource pack doesn't require OptiFine in itself, it require some of its features
 There are Fabric alternatives that provide the OptiFine features too
It should work fine with Fabulously Optimized as long as you add https://github.com/dicedpixels/CITResewn/releases/tag/1.20.4-1.1.4-dicedpixels

**Comment by Ozzy146** [comment]
Just tried it out and it works! Thanks so much!
