### ISSUE TITLE
Conflicts with Durability Viewer Mod. 

### ISSUE THREAD

**Issue by Telepath-Jay** [SkyblockerMod/Skyblocker#606]
### What happened?

Causes crash when going to /hub when using durability viewer mod. It does not happen when either of these mods are used separately. does not happen on islands.  durability viewer mod used https://www.curseforge.com/minecraft/mc-mods/giselbaers-durability-viewer

### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.18.1+1.20.4.jar

**Comment by viciscat** [comment]
Hey could you send the crash report?

**Comment by Telepath-Jay** [comment]
I don't know how to delete this issue. but it was my mistake. i had switched profiles to the old version 1.20.2. it works normally in 1.20.4

**Comment by AzureAaron** [comment]
> I don't know how to delete this issue. but it was my mistake. i had switched profiles to the old version 1.20.2. it works normally in 1.20.4

I can go ahead and close it for you then.
