### ISSUE TITLE
Dungeon waypoint path finder

### ISSUE THREAD

**Issue by Vricken** [SkyblockerMod/Skyblocker#623]
### Describe the new feature.

- [ ] Dungeon secret path finder
- [ ] Next room for blood rush path finder

If it gets implemented I would suggest using optimal but not best algorithms to find path in order to not use too much computational power.

In 1.8.9 a mod called dungeons guide already does this.

**Comment by AzureAaron** [comment]
Isn't the "Next room for blood rush path finder" just like a door highlight (which we have)?

**Comment by Vricken** [comment]
Not exactly, like it renders a path (a simple red line) in game which you follow.

Basically u can turn off ur brain when doing dungeons and beginners don’t get lost in large rooms.

**Comment by Vricken** [comment]
I stand corrected
