### ISSUE TITLE
Option to hide HUD element

### ISSUE THREAD

**Issue by VermeilChan** [SkyblockerMod/Skyblocker#631]
### Describe the new feature.

add an option for hiding HUD element when you press f3.

### Images

![image](https://github.com/SkyblockerMod/Skyblocker/assets/120065660/88a01bb5-9607-455c-8d39-89a311cce6c9)

**Comment by AzureAaron** [comment]
This may or may not be fixed it depends, but if a fix is to happen soonest it'll come is when we release our 1.20.5 version

**Comment by VermeilChan** [comment]
> This may or may not be fixed it depends, but if a fix is to happen soonest it'll come is when we release our 1.20.5 version

ok thank you :D, goo luck 😼

**Comment by AzureAaron** [comment]
> > This may or may not be fixed it depends, but if a fix is to happen soonest it'll come is when we release our 1.20.5 version
> 
> ok thank you :D, good luck 😼

PR #669 fixes this issue.

Now these HUD elements will render behind the F3 screen which should be sufficient.

**Comment by VermeilChan** [comment]
thank you :)
