### ISSUE TITLE
unable to launch 1.17+ using feather client

### ISSUE THREAD

**Issue by Cecease** [SkyblockerMod/Skyblocker#633]
### What happened?

version 1.17 and beyond are unable to be launched using feather client, kinda a big issue since myself and a lot of people i know rely on feather for performance and this is a huge issue

### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.19.1+1.20.4

**Comment by kevinthegreat1** [comment]
Fabric mods provide way better performance. Check out mods such as [Sodium](https://modrinth.com/mod/sodium) or mod packs such as the [Skyblocker Modpack](https://modrinth.com/modpack/skyblocker-modpack). Feather is closed-source, so we literally can not fix it legally.

**Comment by kevinthegreat1** [comment]
In addition, note the controversy regarding feather. See <https://hypixel.net/threads/4801748/>, <https://hypixel.net/threads/4842120/>, and <https://blog.mmpa.info/posts/feathermc-concerns/>.
