### ISSUE TITLE
Powder hud no longer functions as of 0.20.0

### ISSUE THREAD

**Issue by IllagerCaptain** [SkyblockerMod/Skyblocker#644]
### What happened?

There is nothing more to it. It simply doesn't work, it shows as zero powder. I assume this is due to it not recognizing the glacial powder, but if I hide glacial powder in tablist settings it still doesn't work, so there may have been some formatting change.

### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.19.1+1.20.4.jar

**Comment by AzureAaron** [comment]
It’s because the widget changed from “X Powder: (num)” to just “X: (num)”. The fix will be coming soon!

**Comment by AzureAaron** [comment]
Soon after #645 is merged we will release a beta version with the fix for this, until then you can use [this](https://github.com/SkyblockerMod/Skyblocker/actions/runs/8626471421) GitHub Actions build containing my fixes for the powder hud. If there are any issues let me know!
