### ISSUE TITLE
Some basic SkyCrypt integration.

### ISSUE THREAD

**Issue by CuteistFox** [SkyblockerMod/Skyblocker#655]
### Describe the new feature.

Im pretty sure there is a way to have chromium im minecraft or something(liquidbounce(a cheat client i use on p2w server(never hypixel of course)) does this) so it will be nice to have basic skycrypt integration like a button that shows your stats via skycrypt interface(as its better than vannila interface) and same for people you right click and for when yuo hit the name of someone in chat (only the first one will be actuly usefull)

**Comment by Julienraptor01** [comment]
Chromium in minecraft : 💀
We could have a custom GUI similar to the /profileviewer thing from wathever mod that could display the informations from the Hypixel API just like skycrypt, but in a nice way within the game

**Comment by CuteistFox** [comment]
> We could have a custom GUI similar to the /profileviewer thing from wathever mod that could display the informations from the Hypixel API just like skycrypt, but in a nice way within the game

that is a better idea than chromium in minecraft
