### ISSUE TITLE
Tab HUD based widgets cannot be moved properly in their configuration GUIs

### ISSUE THREAD

**Issue by AzureAaron** [SkyblockerMod/Skyblocker#670]
### What happened?

When the tab hud scale is set to anything other than 100% it becomes extremely difficult to move the widgets around in the various HUD configuration screens that use tab hud based widgets and you can only really move them around in the top left quadrant. The screen doesn’t account for scaling which causes this bug. I experience this issue with my scale set to 70% which I need because otherwise the widgets take up a quarter of my screen at 100% as I use GUI scale 7, I shouldn’t be forced to trade usability for configurability.

### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.20.0+1.20.4.jar

**Comment by MacchuPicchu3** [comment]
![2024-08-04_22 52 25](https://github.com/user-attachments/assets/3182caf4-936a-438a-a2e7-977fd08c24d5)

Do you think this is related to this behavior, where my mana bar clips out of its boundaries? Oddly, this happens whenever my mana is low, like below 400

**Comment by AzureAaron** [comment]
> ![2024-08-04_22 52 25](https://private-user-images.githubusercontent.com/105882768/354964622-3182caf4-936a-438a-a2e7-977fd08c24d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjYzNzUsIm5iZiI6MTcyMzE2NjA3NSwicGF0aCI6Ii8xMDU4ODI3NjgvMzU0OTY0NjIyLTMxODJjYWY0LTkzNmEtNDM4YS1hMmU3LTk3N2ZkMDhjMjRkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwMTE0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjYxZTg3N2JlMzVjNWFhMjViZGM0OTA3N2U2YzM4OGIwMWU3OTU5OGRiYTZlZjgwOTgzN2FiODg4ZDY0OWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1ddJhosMsdfYM5WhAGhQJlTFSa2YAkc6sONxaqfB0Ns)
> 
> Do you think this is related to this behavior, where my mana bar clips out of its boundaries? Oddly, this happens whenever my mana is low, like below 400

These issues aren't related, this is about not being able to move hud widgets properly inside of the placement guis.
