### ISSUE TITLE
Shift-left clicking slots in the fancy crafting screen moves items from old crafting screen with InventoryProfileNext installed

### ISSUE THREAD

**Issue by cvrunmin** [SkyblockerMod/Skyblocker#671]
### What happened?

~Yes,~ With InventoryProfileNext installed, if you shift-clicking the 5th slot on the 2nd row of inventory slots in the fancy crafting screen, the "Close" item from the actual crafting screen is "moved" to the hotbar and hence, close the screen. You trigger the "Back" item if you open the crafting screen from Skyblock menu.

If you hold shift-left click and drag from the 2nd or 3rd row of crafting slots to outside of slots, you move the glass pane to the inventory. You also move the glass pane to the hotbar if shift-left clicking the 1st and 2nd row of inventory slots, except 2nd row 5th  slot which is close/back item. These should be caused by the same bug based on the reproducing logic.

EDIT: amending some wordings as it is found to be a mod compatibility issue.

### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.20.0+1.20.4.jar

### Additional context

Full mod list:
- aaron-mod-1.2.2
- architectury-11.1.17
- chatpatches-204.6.2
- citresewn-1.1.4 (dicedpixels' fork)
- cloth-config-13.0.121
- durabilityviewer-1.20.4-fabric0.91.2-1.10.5
- edgelesschatscreen-1.20-1.0.2
- entityculling-fabric-1.6.4-mc1.20.4
- fabric-api-0.96.11+1.20.4
- fabric-language-kotlin-1.10.19+kotlin.1.9.23
- ferritecore-6.0.3
- gamma_shifter-1.0.4
- ImmediatelyFast-1.2.10+1.20.4
- InventoryProfilesNext-1.20.3-1.10.10
- iris-1.6.17
- libIPN-1.20.3-4.0.2
- lithium-mc1.20.4-0.12.1
- modmenu-9.0.0
- ok-boomer-0.1.3+1.20.2
- owo-lib-0.12.5+1.20.3
- reeses_sodium_options-1.7.2+mc1.20.4-build.102
- RoughlyEnoughItems-14.0.688-fabric
- seamless-2.2.2-fabric-1.20.4
- skyblocker-1.20.0+1.20.4
- sodium-extra-0.5.4+mc1.20.4-build.116
- sodium-fabric-0.5.8+mc1.20.4
- tooltip-scroll-1.3.0
- Xaeros_Minimap_24.1.1_Fabric_1.20.4
- XaerosWorldMap_1.38.4_Fabric_1.20.4
- yet-another-config-lib-fabric-3.3.2+1.20.4

**Comment by viciscat** [comment]
well that's quirky

**Comment by cvrunmin** [comment]
> well that's quirky

Even more quirky, if you shift-left click an item from the inventory slot mentioned, the item is moved to the crafting table AND a glass pane is moved to the hotbar. Hope this info gives you more clues.

**Comment by viciscat** [comment]
I can't reproduce?? I can shift click just fine on all the slots. What mods do you have

**Comment by viciscat** [comment]
Thanks for tracking down the cause to there! I will look into it but this might be hard because of kotlin shenanigans

**Comment by viciscat** [comment]
alright so I looked into the code and I think it's cuz it doesn't check if slot.isDisabled()... Can't find it anywhere. So I don't think we can fix it

**Comment by Julienraptor01** [comment]
> alright so I looked into the code and I think it's cuz it doesn't check if slot.isDisabled()... Can't find it anywhere. So I don't think we can fix it

https://github.com/Bawnorton/MixinSquared moment ?
Or PR maybe

**Comment by DonFlymoor** [comment]
As a warning inventory sorting mods are not allowed on Hypixel (depending on the interpretation of gameplay action) 

> Additionally, we do also note that anything which automates any player gameplay action is strictly disallowed,
> be those Minecraft modifications, external software or hardware.
> This includes things such as (but not limited to) auto/burst clicking buttons or macros, auto-sprint, and aim assists.

https://support.hypixel.net/hc/en-us/articles/6472550754962-Hypixel-Allowed-Modifications

**Comment by LifeIsAParadox** [comment]
looks like we cant fix it on our end. You need to open an issue at InventoryProfileNext github.
