### ISSUE TITLE
You can no longer hide bars in-game

### ISSUE THREAD

**Issue by Winqov** [SkyblockerMod/Skyblocker#707]
### What happened?

Since the fancier bars update [#654](https://github.com/SkyblockerMod/Skyblocker/pull/654), you can no longer hide specific bars in-game. Unless I'm missing something, the only way to hide bars now is to edit the skyblocker.json file and change the bar layer to none. This option get reset if you open the bars config screen again.

For instance:
![Screenshot_2024-05-13_10-43-07](https://github.com/SkyblockerMod/Skyblocker/assets/143328169/a429e9ed-0f23-4356-9347-7d7687e655ef)

I suggest adding a "show" or "hide" check box to the bar options to fix this regression.

![Screenshot_2024-05-13_10-59-18](https://github.com/SkyblockerMod/Skyblocker/assets/143328169/f6168bd3-5eef-4656-8cb1-bd61661ef3d8)

### Minecraft Version

1.20.6

### Skyblocker Version

skyblocker-1.20.3-beta.2+1.20.6.jar

**Comment by viciscat** [comment]
it's a bit odd but if you pickup a bar in the config, make sure it doesn't snap to something else (like there isn't a "ghost" version of it) and drop it it should go in the top left but not quite the top left. That will make it not show*

*it is kinda bugged currently, you will need to make the text invisible (turning off show value) and also restarting the game to make it actually go poof. I currently have a PR open to fix that issue
