### ISSUE TITLE
Frequent Crashing

### ISSUE THREAD

**Issue by jmdev91** [SkyblockerMod/Skyblocker#73]
Whenever I get lobbied or disconnected from the server, this mod causes my entire client to crash. Most of the time the logs mention the BackpackPreview class, namely the getSkyblockProfile method. This should not be running when the main menu is up.

**Comment by KonaeAkira** [comment]
Thank you for reporting this! Issue has been fixed.

**Comment by jmdev91** [comment]
Oh, awesome. It's a bit harder to track, because the logs have only mentioned obfuscated minecraft class/method names, but there's also some sort of issue I keep running into involving a double-ended queue (Deque) that only shows up with this mod; looks like it's trying to get the "last" element of an empty deque. It seems to involve a deque that "belongs" to minecraft, but this mod is emptying it out. I know it's not much to go on, but keep an eye out for anything like that.

**Comment by jmdev91** [comment]
Nevermind, think I found out how beta builds work.
