### ISSUE TITLE
Add Polish to hysky translate

### ISSUE THREAD

**Issue by danehcan** [SkyblockerMod/Skyblocker#753]
### Describe the new feature.

Please add polish translation option I can tranlate it.

**Comment by viciscat** [comment]
hey, the person that has the power to add languages to the translation service is currently busy with really life. They should be back by the end of next week :)

**Comment by viciscat** [comment]
Hi me again, turns out I can add a language to the translation service so here it is:
[https://translate.hysky.de/projects/Skyblocker/skyblocker/pl/](https://translate.hysky.de/projects/Skyblocker/skyblocker/pl/)

you just need to login with your GitHub account!
