### ISSUE TITLE
Bars not displaying properly

### ISSUE THREAD

**Issue by Nitaeram** [SkyblockerMod/Skyblocker#758]
### What happened?

title, some mod is causing it and I don't know which :P
Minecraft version 1.20.4 (your version thing allows only 1.20.6)

### Screenshots

![Zrzut ekranu 2024-06-11 135047](https://github.com/SkyblockerMod/Skyblocker/assets/106491218/d5a40e7f-c6e3-43dd-ba1b-0ae0a739d07b)

Mods:

![Zrzut ekranu 2024-06-11 135725](https://github.com/SkyblockerMod/Skyblocker/assets/106491218/f6ad5f81-3503-44ab-b42b-931c76feb85a)
![Zrzut ekranu 2024-06-11 135733](https://github.com/SkyblockerMod/Skyblocker/assets/106491218/1424232a-421b-414e-9804-3ad94f47c097)

### Log output

[latest.log](https://github.com/user-attachments/files/15787378/latest.log)

### Minecraft Version

1.20.6

### Skyblocker Version

skyblocker-1.20.2+1.20.4.jar

**Comment by x-yingcan-x** [comment]
Then upgrade ur client to 1.20.6, support for 1.20.4 is already dropped.
i dont want to be that cruel to u, but the fact is that no one can help u.

**Comment by maboje** [comment]
This is a problem with ImmediatelyFast in combination with Skyblocker, removing it should help your issue.
