### ISSUE TITLE
Improve Crystal Hollows waypoints

### ISSUE THREAD

**Issue by maboje** [SkyblockerMod/Skyblocker#760]
### Describe the new feature.

 I'm suggesting, making the Crystal Hollows waypoints the same way the Dwarven Mines waypoints are made.

Crystal Hollows waypoints currently don't scale with how far you are from them, in opposition to the Dwarven Mines waypoints, which maintain the same size, no matter how far, or close you are to them, making them way easier to see.

The added images show a waypoint in the Dwarven Mines, around 300 blocks away, and a Crystal Hollows waypoint around 150 blocks away. It's impossible to tell what's said on the crystal hollows waypoint.

### Images

![dwarven](https://github.com/SkyblockerMod/Skyblocker/assets/147726736/38db4cef-b56e-48b1-a8e9-aaf3ed084e15)
![crystal](https://github.com/SkyblockerMod/Skyblocker/assets/147726736/dd54a6d1-505a-4c37-98a6-f8547167528b)

**Comment by Mininoob46** [comment]
Skypler has a lot of mining features 
Like better waypoints than that
Recommend to disable the waypoints from chat since it takes alot of space in your chat
https://github.com/btwonion/skylper

**Comment by Mininoob46** [comment]
But still improve the waypoints
