### ISSUE TITLE
Farming hud displays coins/h based on buy order prices

### ISSUE THREAD

**Issue by Emirlol** [SkyblockerMod/Skyblocker#761]
### What happened?

Title. This causes incorrect coins/h displays on some crops, like nether wart. Sell order prices are always around the npc price, but the buy price is often very low. For example, at the time of writing this, the buy order prices are at 1.3 while sell order prices are at 3.9 (NPC price is 4.0). So I see 3.7m/h rather than the actual ~10m I should be making.

### Minecraft Version

1.20.6

### Skyblocker Version

Latest

**Comment by AC19970** [comment]
Thwse functions that involve price calculation should provide an option of which price to use.

**Comment by AC19970** [comment]
These functions that involve price calculation should provide an option of which price to use.

**Comment by Fluboxer** [comment]
if price is lower than NPC then use NPC, else use bz price
