### ISSUE TITLE
Opening any menu in skyblock fully crashes the game.

### ISSUE THREAD

**Issue by 8pn** [SkyblockerMod/Skyblocker#770]
### Minecraft Version

1.20.6

### Skyblocker Version

Skyblocker 1.21.0-beta.1 for 1.20.6

### Reproduction Steps

Going into any menu on Skyblock fully crashes. This includes but isn't limited to any of the menus that are in the UI.

### Crash Report file and latest.log

```shell
The game crashed whilst rendering screen
Error: java.lang.UnsupportedOperationException
```

**Comment by 8pn** [comment]
Most likely "EMI" that causes the issue.

**Comment by LifeIsAParadox** [comment]
do you still have this issue? if so could you also send the full latest.log file? By uploading it to [mclo.gs](https://mclo.gs/) and sending the link here

**Comment by LifeIsAParadox** [comment]
I am closing this issue as no further information has been provided. Most probably this bug is fixed in the stable version.
Or #812 will fix the Issue.
