### ISSUE TITLE
Crystal hallows treasure chest solver

### ISSUE THREAD

**Issue by isidentical** [SkyblockerMod/Skyblocker#776]
### Describe the new feature.

Implement a chest solver akin to Skytils: https://github.com/Skytils/SkytilsMod/blob/039cb1b146b1e3f71d1858a32613281afc45297f/src/main/kotlin/gg/skytils/skytilsmod/features/impl/mining/StupidTreasureChestOpeningThing.kt

**Comment by Mininoob46** [comment]
Skypler have it
https://github.com/btwonion/skylper

**Comment by AzureAaron** [comment]
This was added in #849, download the latest beta to get it today or wait for 1.22.0 release :)
