### ISSUE TITLE
Crash on donating special item to museum

### ISSUE THREAD

**Issue by russellbanks** [SkyblockerMod/Skyblocker#803]
### Minecraft Version

1.21.0

### Skyblocker Version

1.21.0+1.21

### Reproduction Steps

The crash happened on clicking confirm when donating a [Polished Pebble](https://hypixel-skyblock.fandom.com/wiki/Polished_Pebble) to the museum as a special item.

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-06-25 22:25:15
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectOpenHashSet.add(Object)" because the return value of "de.hysky.skyblocker.skyblock.item.MuseumItemCache$ProfileMuseumData.collectedItemIds()" is null
	at de.hysky.skyblocker.skyblock.item.MuseumItemCache.handleClick(MuseumItemCache.java:118)
```

### Additional context

This could happen with other items but this was the first item special item I tried donating after updating to Skyblocker 1.21.0+1.21 from 1.21.0+1.20.6.

**Comment by LifeIsAParadox** [comment]
Could you also send the full latest.log file? By uploading it to [mclo.gs](https://mclo.gs/) and sending the link here

**Comment by russellbanks** [comment]
https://mclo.gs/1kIEhVK

**Comment by Julienraptor01** [comment]
we are likely missing a check and some handling of a situation right here
https://github.com/SkyblockerMod/Skyblocker/blob/1f7c90515c0be657fd70abdb09222d6744fbc508/src/main/java/de/hysky/skyblocker/skyblock/item/MuseumItemCache.java#L118

**Comment by jaideep-kalagara** [comment]
I have the same issue and have no idea how to fix it

**Comment by LifeIsAParadox** [comment]
this build should fix the problem **[\[download\]](https://nightly.link/SkyblockerMod/Skyblocker/actions/runs/9687022604/skyblocker-1.21.0-beta-9a59ee7%2B1.21.zip)**
