### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by x-yingcan-x** [SkyblockerMod/Skyblocker#823]
### What happened?

everytime, within 1min of begin in dungeon, my game frozen for a period.

### Log output

[latest.log](https://github.com/user-attachments/files/16123526/latest.log)
check line 9209\~9254 
and 9385\~9543 for a strange error spam

### Minecraft Version

1.21.0

### Skyblocker Version

skyblocker-1.21.1-alpha-a61def4+1.21

**Comment by kevinthegreat1** [comment]
Thanks for your report. I think it's caused by the pr linked above.

**Comment by AzureAaron** [comment]
This feature has been remade in #888 where the issue should be solved.
