### ISSUE TITLE
Chocolate Eggs have ESP

### ISSUE THREAD

**Issue by nea89o** [SkyblockerMod/Skyblocker#832]
### What happened?

The chocolate egg finder detects armor stands through walls impossible to see by the player. Hypixel does not really allow ESP like that, a proper approach would be to use the particles from the egglocater instead.

### Screenshots

![image](https://github.com/SkyblockerMod/Skyblocker/assets/20768569/9cb0177e-4eec-41db-aeae-c5918dab0574)
This egg was detected without me ever seeing it or getting it shared in chat.

### Log output

https://mclo.gs/J1NFRDp

### Minecraft Version

1.21.0

### Skyblocker Version

1.21.1+1.21

**Comment by x-yingcan-x** [comment]
skyblocker sends the egg positions to you, and only to you, click them to share.
(and a useless thing, tell u where u find it after u already found)

**Comment by nea89o** [comment]
Skyhanni uses the visible particles from the detector, skyblocker scans the world for armor stands even when behind walls

**Comment by Fluboxer** [comment]
pretty sure no armorstands involved in it

**Comment by AzureAaron** [comment]
Skyblocker listens to armour stand entity update packets, we don't actively scan the world just to clarify this but the functionality should still be changed

**Comment by nea89o** [comment]
> pretty sure no armorstands involved in it, at least in way you say

https://github.com/SkyblockerMod/Skyblocker/blob/4233a55c009d2a751832d42f67f6dad1987abb18/src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/EggFinder.java#L84-L106 it definitely uses armor stand to detect things

**Comment by XPed0bearZQZE** [comment]
> > pretty sure no armorstands involved in it, at least in way you say
> 
> https://github.com/SkyblockerMod/Skyblocker/blob/4233a55c009d2a751832d42f67f6dad1987abb18/src/main/java/de/hysky/skyblocker/skyblock/chocolatefactory/EggFinder.java#L84-L106
> it definitely uses armor stand to detect things

https://github.com/SkyblockerMod/Skyblocker/blob/master/src/main/java/de/hysky/skyblocker/mixins/ClientPlayNetworkHandlerMixin.java#L114-L124

as we said, it depends on packets not scanning entities

but it's indeed cheaty rn, and we will nerf it
