### ISSUE TITLE
Translation related

### ISSUE THREAD

**Issue by AC19970** [SkyblockerMod/Skyblocker#846]
### Describe the new feature.

Word order in other languages ​​may not be exactly the same as in English, so please avoid line breaks in the middle of a sentence. For example, skyblocker.reorderHelper.tooltip.line1 and skyblocker.reorderHelper.tooltip.line2. Also, some strings still cannot be translated, like Square and Circular (skyblocker.config.general.itemInfoDisplay.itemRarityBackgroundStyle). This kind of part with only a few fixed options should be translatable like text.skyblocker.open.

**Comment by kevinthegreat1** [comment]
Thanks for reporting, well definitely try to make texts translatable and get this fixed.

**Comment by AzureAaron** [comment]
#932 Fixes these issues :)

We plan to release on the weekend so if you wanna get translations in for these new strings you might wanna do it soon after the PR is merged, you can subscribe to notifications to get an email about when that happens.

Happy translating!
