### ISSUE TITLE
rare NullPointerException in order term solver

### ISSUE THREAD

**Issue by x-yingcan-x** [SkyblockerMod/Skyblocker#847]
### What happened?

im cursed by NullPointerException

### Log output

[latest.log](https://github.com/user-attachments/files/16236352/latest.log)

### Minecraft Version

1.21.0

### Skyblocker Version

skyblocker-1.21.1-alpha-2ebf622+1.21

**Comment by kevinthegreat1** [comment]
This order terminal code is confusing me ngl.

**Comment by kevinthegreat1** [comment]
Can you see if #848 solves your issue?

**Comment by kevinthegreat1** [comment]
Download link: https://github.com/SkyblockerMod/Skyblocker/actions/runs/9942446857/artifacts/1702509625.

**Comment by x-yingcan-x** [comment]
this rlly hard to test, i only faced this issue around 4 times, did 500+ f7
