### ISSUE TITLE
Fancy Bars Broken By New Update

### ISSUE THREAD

**Issue by lonelybaloney** [SkyblockerMod/Skyblocker#87]
The fancy bars feature seems to have been broken by a semi-recent skyblock update, like the health bars in SBA. The best fix seems to be what SBA did, which is to use a patterns to parse the action bar and get health, mana, defense, etc. data from it, and import this, keeping the old regeneration prediction system with some modifications for the new health regeneration stat.

**Comment by KonaeAkira** [comment]
Fixed on the 1.19 branch
