### ISSUE TITLE
Ultrasequencer solver sometimes shows incorrect solution

### ISSUE THREAD

**Issue by MacchuPicchu3** [SkyblockerMod/Skyblocker#892]
### What happened?

Skyblocker's solvers for ultrasequencer (from experimentation table) will sometimes show an incorrect solution. If you solve a round correctly, the mod will sometimes show the solution from that previously completed round in the next one. (Somewhat related: if the player has hideEmptyTooltips enabled, this glitch will softlock the ultrasequencer).

This seems to happen most often when the player finishes the first round very quickly, so it's most easily replicable on round 2. Just click the solution for round 1 as fast as possible and there's a chance it will glitch out afterwards.

### Minecraft Version

1.21.0

### Skyblocker Version

1.21.1

**Comment by AC19970** [comment]
In fact, there is more to it than that. If you quickly click on the visitor's order in the garden, the order content will still be displayed in the shopping list. This is probably a problem when the mod handles click events. As for the situation, sometimes it is related to network latency. I often encounter this problem when the network is stuck, that is, the clicks that have been submitted are inconsistent with the clicks that the module judges me to have submitted, and therefore it is still judged that I am in the previous round.

**Comment by AzureAaron** [comment]
> In fact, there is more to it than that. If you quickly click on the visitor's order in the garden, the order content will still be displayed in the shopping list. This is probably a problem when the mod handles click events. As for this situation, sometimes it is related to network latency. I often encounter this problem when the network is stuck, that is, the clicks that have been submitted are inconsistent with the clicks that the module judges me to have submitted, and therefore it is still judged that I am in the previous round.

Yeah my friend discovered it too, while ping might affect it I suspect the real cause is due to the screen being ticked on the client (and the visitor being re-added) before the screen can be closed.
