### ISSUE TITLE
Improvement to README.md

### ISSUE THREAD

**Issue by AC19970** [SkyblockerMod/Skyblocker#910]
Not a feature request for the mod itself, but Github insists on me choosing an issue template...

Well, what I want to say is that we can use weblate's translation progress svg instead of using this unsuitable percentage progress.

[![Translate status](https://translate.hysky.de/widget/Skyblocker/multi-auto.svg)](https://translate.hysky.de/projects/Skyblocker/skyblocker/)

Since we can use language fallback, it is unnecessary to increase the translation progress of languages ​​such as en-ca and zh-hk to 100%, so I think this is more appropriate.

**Comment by AC19970** [comment]
In addition, the **Chinese** in the translator section should be **Chinese (Traditional)**.

**Comment by AzureAaron** [comment]
Fixed by #926.
