### ISSUE TITLE
1.22.0 not compatile with 1.21

### ISSUE THREAD

**Issue by Charismara** [SkyblockerMod/Skyblocker#941]
### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

skyblocker-1.22.0+1.21.1

### Reproduction Steps

- Create a 1.21 Profile
- Install Skyblocker 1.22.0
- Crash

### Crash Report file and latest.log

```shell
https://mclo.gs/Ul8Ff93
```

### Additional context
When the version break is intended then please remove the `1.21` version from Modrinth
![image](https://github.com/user-attachments/assets/b9ef2d2e-3615-462c-bf43-73b9e9cba2f0)

**Comment by AzureAaron** [comment]
The 1.21.1 versions of FAPI should be backwards compatible and work on 1.21, if this isn't the case let us know.
