### ISSUE TITLE
When using shortcuts, if a thing is typed (ie: /g), all followup text will be ignored (ie: /g help)

### ISSUE THREAD

**Issue by loopzys** [SkyblockerMod/Skyblocker#956]
### What happened?

I was trying to make a warp to my garden, which I put in as "/g". I also tried to use the shortened guild commands "/g help" It immediately teleports to garden, instead of using the followup text as the actual command.

### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

skyblocker-1.21.1 version

**Comment by kevinthegreat1** [comment]
Make sure you put the shortcut in the `Command` section, not the `Command Argument` section.
