### ISSUE TITLE
Mana bar HUD overflows visually if max intelligence is too low

### ISSUE THREAD

**Issue by MacchuPicchu3** [SkyblockerMod/Skyblocker#966]
### What happened?

Screenshot is provided. This seems to occur most commonly whenever my max intelligence dips below ~500 - for example, when collecting heavy pearls at the Matriarch.

### Screenshots

![Screenshot 2024-08-29 at 10 11 04](https://github.com/user-attachments/assets/8fe76937-d506-4401-91b6-6dffc1677cf9)

### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

Skyblocker 1.22.0

### Additional context

GUI scale is set to 3x (using Sodium latest version)

**Comment by AzureAaron** [comment]
This was fixed with the addition of 1.21.4 support.
