### ISSUE TITLE
Mod Publishing TODOs

### ISSUE THREAD

**Issue by AzureAaron** [SkyblockerMod/Skyblocker#974]
### What happened?

- Fix release name
- Add JEI as optional dependency
- Add YACL as embedded dependency

### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

skyblocker-1.22.1+1.21.1.jar

**Comment by x-yingcan-x** [comment]
> Add YACL as embedded dependency

is it a good idea?

**Comment by AzureAaron** [comment]
> > Add YACL as embedded dependency
> 
> Is it a good idea? I mean why embed it rather than just require it.

We have been embedding YACL since we began using it a year ago, this is just marking it as such on Modrinth.
