### ISSUE TITLE
Dungeon room secrets are displayed incorrectly

### ISSUE THREAD

**Issue by BestZx0521** [SkyblockerMod/Skyblocker#981]
### What happened?

Sometimes the dungeon secrets don't show items secrets , or don't show anything at all secrets 

![eb05e953e7ca5a9bffb675dce7656863](https://github.com/user-attachments/assets/a4a2fe1d-3cfb-476a-b6b0-a452844146fb)

### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

skyblocker-1.22.0+1.21.1.jar

**Comment by AzureAaron** [comment]
Was the whole dungeon affected by this bug or only the one room?

**Comment by BestZx0521** [comment]
> Was the whole dungeon affected by this bug or only the one room?

All , but sometime only 1.

After the end
[Skyblocker] IndoorRaptor0712 found 3secrets。ℹ(Data not cached)

Is it my setting problem?

![feea190d42d8be1aabade3e14c3b7423](https://github.com/user-attachments/assets/838d6c0c-0879-4600-ae90-a737acc75039)

![image](https://github.com/user-attachments/assets/7e610aea-c445-492d-8b03-7ae70eb318be)

**Comment by kevinthegreat1** [comment]
Can you try running `/skyblocker dungeons secrets markAsMissing all` the next time you encounter this?

**Comment by BestZx0521** [comment]
> 下次遇到这种情况时，您可以尝试运行吗？`/skyblocker dungeons secrets markAsMissing all`

okay
