### ISSUE TITLE
Consistent Crash with Iris

### ISSUE THREAD

**Issue by LordOfTheWeebs** [SkyblockerMod/Skyblocker#988]
### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

skyblocker-1.22.2+1.21.1.jar

### Reproduction Steps

1. Load the mod with Iris in the mods folder.

### Additional context

I was originally thinking it was an issue with a different mod because of what was listed in the crash report, but I found out it was Iris from a test instance with only the necessities (Fabric API and Skyblocker, then adding Sodium, then adding Iris).
[crash-2024-09-03_17.10.48-client.txt](https://github.com/user-attachments/files/16856173/crash-2024-09-03_17.10.48-client.txt)
[latest.log](https://github.com/user-attachments/files/16856176/latest.log)

**Comment by AzureAaron** [comment]
Updating to Fabric Loader 0.16.4 will fix this issue.
