### ISSUE TITLE
Game crashed when trying to open config.

### ISSUE THREAD

**Issue by absolore** [SkyblockerMod/Skyblocker#990]
### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

skyblocker-1.21.1+1.21.jar

### Reproduction Steps

When trying to open the config, game crashes.

### Additional context

Using fabric-loader-0.16.4-1.21 and fabric-api-0.102.0+1.21.jar

[crash-2024-09-04_13.12.03-client.txt](https://github.com/user-attachments/files/16875252/crash-2024-09-04_13.12.03-client.txt)

[latest.log](https://github.com/user-attachments/files/16875259/latest.log)

**Comment by AzureAaron** [comment]
Updating to Skyblocker 1.22.2 will fix this issue, btw Fabric API’s 1.21.1 versions work fine on regular 1.21 so you don’t need to update Minecraft if you don’t want to.
