### ISSUE TITLE
cant access the settings

### ISSUE THREAD

**Issue by thatAngryfish** [SkyblockerMod/Skyblocker#995]
### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

1.20.6

### Reproduction Steps

I just go in the settings and it insta crash

### Crash Report file and latest.log

```shell
The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: Cannot read field "item" because "button.itemData" is null
```

**Comment by AzureAaron** [comment]
You can fix this by either deleting your config file or by updating to our latest version for Minecraft 1.21.1 (Skyblocker 1.22.2)
