### ISSUE TITLE
Some features are broken

### ISSUE THREAD

**Issue by AC19970** [SkyblockerMod/Skyblocker#997]
### Version

Fabric 0.16.5
Fabric API 0.104.0+1.21.1
Minecraft 1.21.1
skyblocker-1.22.2-beta-3b344cd+1.21.1

### Problems

Experimentation table helper is not working at all. (Sometimes it just doesn't work, but sometimes the mod prevents me from clicking just like I'm clicking wrong block.)
<del>BIN avg price is not displayed since many days ago.</del> Fixed.
All highlight is not working now.

I'm not sure if I'm the only one having this problem. If anyone uses same version and doesn't have same problems, I'd check to see if there's a conflicting mod.

**Comment by AC19970** [comment]
> im using `skyblocker-1.22.2-beta-bd6ed47+1.21.1`(latest rn), none of these problems happen to me, but hypixel mod API do acts weirdly for me, cant refresh token very often. maybe update ur skyblocker first?

I built the latest version and nothing changed. There are only two changes between the two versions that should not be relevant to the problem. I have only recently updated the Fabric and Minecraft versions. I'll check for possible conflicting mods later.

**Comment by AC19970** [comment]
ctrl+left click to copy bazaar order also doesn't work...

**Comment by AC19970** [comment]
Uh, it's not Indium, it's Silk...

**Comment by AC19970** [comment]
I think Silk should be marked as an incompatible mod…

**Comment by kevinthegreat1** [comment]
It seems like it hasn't been updated in a while.

**Comment by AC19970** [comment]
It is used by Veinminer, which is still being updated. This issue should only occur for players who are not using multi-instancing.

**Comment by AC19970** [comment]
ReplayMod also makes highlights broken. really weird

**Comment by kevinthegreat1** [comment]
Replay mod wraps all screens, I think this is known before.
